project:
  type: website
  output-dir: docs

website:
  title: "dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Starwars
      - penguins.qmd

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

