project:
  type: website
  output-dir: docs

website:
  title: "dashboards"
  navbar:
    left:
      - href: index.qmd
        text: Starwars
      - href: penguins.qmd
        text: Penguins
      - icon: bookmark-heart-fill
        href: https://gracesstew.github.io
        target: blank

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

